services:
  backend:
    image: 729049749833.dkr.ecr.us-east-1.amazonaws.com/portfolio-backend:latest
    container_name: portfolio-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: 729049749833.dkr.ecr.us-east-1.amazonaws.com/portfolio-frontend:latest
    container_name: portfolio-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
