# Generated by Django 4.2.11 on 2026-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('company', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=180)),
                ('period', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=180)),
                ('url', models.URLField(blank=True)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deliverables', models.JSONField(default=list)),
                ('tech', models.JSONField(default=list)),
                ('metric', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=120)),
                ('excerpt', models.TextField()),
                ('content', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tools', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=50)),
                ('category_label', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tech', models.JSONField(default=list)),
                ('metrics', models.CharField(max_length=180)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=180)),
                ('tagline', models.TextField()),
                ('status', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('current_work', models.TextField()),
                ('future_direction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('key', models.SlugField(unique=True)),
                ('title_primary', models.CharField(max_length=100)),
                ('title_secondary', models.CharField(max_length=120)),
                ('accent_color', models.CharField(default='#00e5ff', max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True)),
                ('icon', models.CharField(default='↗', max_length=8)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
