# Generated by Django 4.2.11 on 2026-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.TextField(blank=True),
        ),
    ]
